[env:attiny412]
platform = atmelmegaavr
board = ATtiny412
framework = arduino

upload_protocol = serialupdi

board_build.f_cpu = 10000000L

monitor_speed = 1200
monitor_port = COM3

upload_speed = 9600